<?php

declare(strict_types=1);

namespace Zinc\Core\Command\Middleware;

use Zinc\Core\Command\Command as C;

class EventBusMiddleware extends AbstractCommandHandlerMiddleware implements CommandHandlerMiddleware
{
    #[\Override]
    public function after(C $command, mixed $result): mixed
    {
        return parent::after($command, $result); // TODO: Change the autogenerated stub
    }

    #[\Override]
    public function before(C $command): void
    {
        parent::before($command); // TODO: Change the autogenerated stub
    }
}
