<?php

declare(strict_types=1);

namespace Zinc\Core\Command\Middleware;

use Zinc\Core\Command\Command as C;

class OutboxMiddleware extends AbstractCommandHandlerMiddleware implements CommandHandlerMiddleware
{
    #[\Override]
    public function after(C $command, mixed $result): mixed
    {
        return parent::after($command, $result); // TODO: Change the autogenerated stub
    }
}
