<?php
declare(strict_types=1);

namespace Zinc\Core\Command\Middleware;

use Zinc\Core\Command\Command as C;

class RetryMiddleware extends AbstractCommandHandlerMiddleware implements CommandHandlerMiddleware
{
    #[\Override] public function before(C $command)
    {
        return parent::before($command); // TODO: Change the autogenerated stub
    }
}