services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # QUERY HANDLER
    Common\Application\Bus\Port\EventBus:
        class: Common\Infrastructure\Bus\Event\EventBus

    Iam\Application\Handlers\Event\UserRegisteredEventHandler:
    Iam\Application\Handlers\Event\UserPasswordRequestedEventHandler:

    #User\Infrastructure\Bus\Event\EventHandler:
    #    tags:
    #        - { name: 'messenger.message_handler', bus: 'messenger.bus.default', method: 'handle' }