services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # QUERY HANDLER
    Common\Application\Bus\Port\QueryBus:
        class: Common\Infrastructure\Bus\Query\QueryBus

    Iam\Application\Handlers\Query\FindUserByEmailQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Iam\Application\Handlers\Query\FindUserByEmailQuery' }