version: '3'

services:
  service-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
    networks:
      - service_network

networks:
  service_network:
    external: true