version: '3'

services:
  service-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
      - ../../var/logs:/var/www/logs:rw
    networks:
      - service_network
    environment:
      - APP_LOG_DIR=/var/www/logs
    user: root

networks:
  service_network:
    external: true

volumes:
  logs_volume:
    external: true
