services:
    _defaults:
        autowire: true
        autoconfigure: true


    Track\Application\:
        resource: '../../src/Application/'

    Track\Domain\:
        resource: '../../src/Domain/'

    Track\Infrastructure\:
        resource: '../../src/Infrastructure/'

    Track\Delivery\:
        resource: '../../src/Delivery/'

    Track\Delivery\Http\Controller\:
        resource: '../../src/Delivery/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

