services:
    _defaults:
        autowire: true
        autoconfigure: true

    Track\Application\Command\HealthCheckCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Track\Application\Command\HealthCheckCommand' }

    Track\Application\Command\CreateTrackCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Track\Application\Command\CreateTrackCommand' }

