services:
    _defaults:
        autowire: true
        autoconfigure: true

    Track\Application\Handlers\Event\HealthCheckEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Track\Application\Event\TrackCreatedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Track\Domain\Event\HealthCheckOk:
        tags:
            - { name: 'event.domain_event', channel: 'track', transport: 'sync' }

    Track\Domain\Event\TrackCreated:
        tags:
            - { name: 'event.domain_event', channel: 'track', transport: 'async' }

    # Track\Application\Handlers\Event\UserRegisteredEventHandler:
    #    tags:
    #        - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    # Track\Application\Handlers\Event\UserPasswordRequestedEventHandler:
    #    tags:
    #        - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }