services:
    _defaults:
        autowire: true
        autoconfigure: true

    Track\Application\Query\Port\TrackQueryBuilder:
        class: Track\Infrastructure\Query\Doctrine\TrackQueryBuilder
        public: true

    Track\Application\Query\HealthCheckQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Track\Application\Query\HealthCheckQuery' }

    Track\Application\Query\TrackListQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Track\Application\Query\TrackListQuery' }