services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    # Track\Application\Handlers\Query\Repository\Port\UserCredentialsRepository:
    #    class: Iam\Infrastructure\Persistence\Doctrine\Repository\UserCredentialsRepository
    #    public: true

    Track\Domain\Repository\Port\HealthCheckRepository:
        class: Track\Application\Repository\HealthCheckRepository
        public: true
