monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - app

when@dev:
    monolog:
        handlers:
            app:
                type: stream
                path: '%kernel.logs_dir%/app.log'  # Путь к файлу, куда будут записываться логи
                level: debug
                channels: [ 'app' ]
                formatter: monolog.formatter.session_request
            # Обработчик для логов Doctrine
            doctrine:
                type: stream
                path: '%kernel.logs_dir%/doctrine.log'
                level: info
                channels: [ 'doctrine' ]

            # Обработчик для системных логов
            main:
                type: stream
                path: '%kernel.logs_dir%/system.log'
                level: error
                channels: [ '!app', '!doctrine' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
