nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', POST', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': ~