services:
    _defaults:
        autowire: true
        autoconfigure: true

    Template\Application\Handlers\Query\HealthCheckQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Template\Application\Handlers\Query\HealthCheckQuery' }