services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    # Template\Application\Handlers\Query\Repository\Port\UserCredentialsRepository:
    #    class: Iam\Infrastructure\Persistence\Doctrine\Repository\UserCredentialsRepository
    #    public: true

    Template\Domain\Repository\Port\HealthCheckRepository:
        class: Template\Application\Repository\HealthCheckRepository
        public: true
