services:
    _defaults:
        autowire: true
        autoconfigure: true


    Ride\Application\:
        resource: '../../src/Application/'

    Ride\Domain\:
        resource: '../../src/Domain/'

    Ride\Infrastructure\:
        resource: '../../src/Infrastructure/'

    Ride\Delivery\:
        resource: '../../src/Delivery/'

    Ride\Delivery\Http\Controller\:
        resource: '../../src/Delivery/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

