services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ride\Application\Command\HealthCheckCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\HealthCheckCommand' }


    Ride\Application\Command\CreateRideCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\CreateRideCommand' }

    Ride\Application\Command\UpdateRideCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\UpdateRideCommand' }

    Ride\Application\Command\JoinRideCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\JoinRideCommand' }


    Ride\Application\Command\RequestJoinRideCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\RequestJoinRideCommand' }

    Ride\Application\Command\AcceptJoinRideCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Command\AcceptJoinRideCommand' }

