services:
    _defaults:
        autowire: true
        autoconfigure: true

    # EVENTS
    Ride\Domain\Event\RiderRequestedJoinToRide:
        tags:
            - { name: 'event.domain_event', channel: 'ride', transport: 'sync' }

    Ride\Domain\Event\RiderRequestAcceptedJoinToRide:
        tags:
            - { name: 'event.domain_event', channel: 'ride', transport: 'async' }

    Ride\Domain\Event\RideCreated:
        tags:
            - { name: 'event.domain_event', channel: 'ride', transport: 'async' }

    Ride\Domain\Event\TrackCreated:
        tags:
            - { name: 'event.domain_event', channel: 'track', transport: 'async', external: 'track.domain.event.track_created' }

    # HANDLERS
    Ride\Application\Handlers\Event\HealthCheckEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\RideCreatedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\RideUpdatedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\RiderJoinedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\RiderJoinRequestedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\RiderJoinAcceptedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Ride\Application\Handlers\Event\TrackCreatedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    # Ride\Application\Handlers\Event\UserRegisteredEventHandler:
    #    tags:
    #        - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    # Ride\Application\Handlers\Event\UserPasswordRequestedEventHandler:
    #    tags:
    #        - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }