services:
    _defaults:
        autowire: true

    Ride\Application\Projector\Port\HealthCheckProjector:
        class: Ride\Infrastructure\Projector\Doctrine\HealthCheckProjector

    Ride\Application\Projector\Port\RideUpdatedProjector:
        class: Ride\Infrastructure\Projector\Doctrine\RideUpdatedProjector

    Ride\Application\Projector\Port\RideCreatedProjector:
        class: Ride\Infrastructure\Projector\Doctrine\RideCreatedProjector

    Ride\Application\Projector\Port\RiderJoinedProjector:
        class: Ride\Infrastructure\Projector\Doctrine\RideJoinedProjector

    Ride\Application\Projector\Port\RiderRequestedJoinToRideProjector:
        class: Ride\Infrastructure\Projector\Doctrine\RideJoinRequestedProjector

    Ride\Application\Projector\Port\RiderRequestAcceptedJoinToRideProjector:
        class: Ride\Infrastructure\Projector\Doctrine\RideJoinRequestAcceptedProjector
