services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ride\Application\Handlers\Query\HealthCheckQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Handlers\Query\HealthCheckQuery' }