services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ride\Application\Query\HealthCheckQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Query\HealthCheckQuery' }

    Ride\Application\Query\RideDataTableQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Query\RideDataTableQuery' }

    Ride\Application\Query\FindRideByIdQueryHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Ride\Application\Query\FindRideByIdQuery' }






