version: '3'
services:
  api_gateway:
    image: nginx:latest
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    networks:
      - service_network

networks:
  service_network:
    external: true