imports:
    - { resource: ../prod/app.yaml }
    - { resource: ../prod/queries.yaml }
    - { resource: ../prod/commands.yaml }
    - { resource: ../prod/events.yaml }
    - { resource: ../prod/outbox.yaml }
    - { resource: ../prod/user.yaml }
