version: '3'

services:
  iam-service-scheduler:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-scheduler
    volumes:
      - ./:/var/www/html

  iam-service-consumer:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-consumer
    volumes:
      - ./:/var/www/html
    environment:
      - CONSUMER_CHANNEL=iam

  iam-service-fpm:
    extends:
      file: ../infrastructure/php/php-fpm/compose.yaml
      service: service-fpm
    volumes:
      - ./:/var/www/html

networks:
  service_network:
    external: true

volumes:
  logs_volume:
    external: true