version: '3'

services:
  iam-service:
    build:
      context: .
      dockerfile: ../infrastructure/php/supervisor/Dockerfile
    volumes:
      - ./:/var/www/html
      - ../common/:/var/www/common
      - ../infrastructure/php/supervisor/etc/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - service_network

  iam-service-fpm:
    build:
      context: .
      dockerfile: ../infrastructure/php/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ../common/:/var/www/common
    networks:
      - service_network

###> doctrine/doctrine-bundle ###
  database:
    extends:
      file: ../infrastructure/postgres/compose.yaml
      service: database
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  service_network:
    external: true