version: '3'

services:
  template-service-scheduler:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-scheduler
    volumes:
      - ./:/var/www/html

  template-service-consumer:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-consumer
    volumes:
      - ./:/var/www/html
    environment:
      - CONSUMER_CHANNEL=template

  template-service-fpm:
    extends:
      file: ../infrastructure/php/php-fpm/compose.yaml
      service: service-fpm
    volumes:
      - ./:/var/www/html

networks:
  service_network:
    external: true
