version: '3'

services:
  service-scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
      - logs_volume:/var/www/logs:rw
      - ./etc/scheduler/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - service_network
    environment:
      - APP_LOG_DIR=/var/www/logs
  service-consumer:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
      - logs_volume:/var/www/logs:rw
      - ./etc/consumer/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - service_network
    environment:
      - APP_LOG_DIR=/var/www/logs

networks:
  service_network:
    external: true

volumes:
  logs_volume:
    external: true
