version: '3'

services:
  service-scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
      - ../../../var/:/var/www/var
      - ./etc/scheduler/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - service_network
  service-consumer:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../../common/:/var/www/common
      - ../../../var/:/var/www/var
      - ./etc/consumer/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - service_network

networks:
  service_network:
    external: true