version: "3"

server:
  command: "php worker.php"

http:
  address: 0.0.0.0:8080
  pool:
    debug: true
    num_workers: 4

watcher:
  enabled: true
  patterns: [".php"]
# do not use development mode in production
logs:
  level: debug
  mode: development
