services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8280:8080"
    environment:
      RR_MAX_REQUESTS: "1000"
      XDEBUG_CONFIG: "client_host=${XDEBUG_REMOTE_HOST} log_level=0 client_port=9005 start_with_request=yes idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=roadrunner"
    volumes:
      - ./:/app
      - ../core/:/core
