services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Psr\Log\LoggerInterface:
    alias: 'monolog.logger'
    public: true

  Denysov\Demo\Delivery\Http\:
    resource: '../src/Delivery/Http/'
    tags: [ 'controller.service_arguments' ]

  Denysov\Demo\Application\:
    resource: '../src/Application/'

  _instanceof:
    Zinc\Core\Command\CommandHandlerInterface:
      tags: ['messenger.message_handler']

  Zinc\Core\Command\CommandBusInterface:
    class: Zinc\Core\Command\Bridge\Symfony\MessengerCommandBus

  Zinc\Core\Event\EventBusInterface:
    class: Zinc\Core\Event\Bridge\Symfony\MessengerEventBus