services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Denysov\Demo\Delivery\Http\:
    resource: '../src/Delivery/Http/'
    tags: [ 'controller.service_arguments' ]

  Denysov\Demo\Application\:
    resource: '../src/Application/'
