version: '3'

services:
  ride-service-scheduler:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-scheduler
    volumes:
      - ./:/var/www/html

  ride-service-consumer:
    extends:
      file: ../infrastructure/php/supervisor/compose.yaml
      service: service-consumer
    volumes:
      - ./:/var/www/html
    environment:
      - CONSUMER_CHANNEL=ride

  ride-service-fpm:
    extends:
      file: ../infrastructure/php/php-fpm/compose.yaml
      service: service-fpm
    volumes:
      - ./:/var/www/html

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':3010'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:3010/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - service_network
    ports:
      - 3010:3010
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

networks:
  service_network:
    external: true

volumes:
  logs_volume:
    external: true

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
