services:
    _defaults:
        autowire: true
        autoconfigure: true


    Iam\Application\:
        resource: '../../src/Application/'

    Iam\Domain\:
        resource: '../../src/Domain/'

    Iam\Infrastructure\:
        resource: '../../src/Infrastructure/'

    Iam\Delivery\:
        resource: '../../src/Delivery/'

    Iam\Delivery\Http\Controller\:
        resource: '../../src/Delivery/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

