services:
    _defaults:
        autowire: true
        autoconfigure: true

    # EVENTS
    Iam\Domain\Event\UserRegistered:
        tags:
            - { name: 'event.domain_event', channel: 'iam', transport: 'async' }

    Iam\Application\Handlers\Event\UserRegisteredEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

    Iam\Application\Handlers\Event\UserPasswordRequestedEventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }